---
- name: Disable systemd-resolved
  ansible.builtin.systemd_service:
    name: "systemd-resolved"
    enabled: false
    state: stopped
  register: disable_systemd
  failed_when: "disable_systemd.status.Result != 'Success' and 'Could not find the requested service' not in disable_systemd.msg | default({})"

- name: Deploy resolv.conf
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
    follow: false
