---
- name: Install HAProxy packages
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: haproxy
    mode: "u=rw,g=r,o="
    validate: /usr/sbin/haproxy -c -f %s
  register: haproxy_conf

- name: Enable HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: started
    enabled: true

- name: Reload HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: reloaded
