---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Basic configuration
      ansible.builtin.import_role:
        name: essential
      tags: essential

    - name: Deploy test container
      ansible.builtin.import_role:
        name: test_http
      vars:
        test_user: test-http
        test_dir: /srv/winkus
        test_port: 8000
      tags: test
      when: "'test_http' in group_names"

    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      when: "'ingress' in group_names"
      tags: caddy
