---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Basic configuration
      ansible.builtin.import_role:
        name: essential
      tags: essential

    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      when: "'ingress' in group_names"
      tags: caddy
      vars:
        caddy_data_path: "/var/lib/caddy_c"

    - name: Deploy HAProxy
      ansible.builtin.import_role:
        name: haproxy
      when: "'haproxy' in group_names"
      tags: haproxy

    - name: Deploy ddclient
      ansible.builtin.import_role:
        name: ddclient
      when: "'ingress' in group_names"
      tags: ddclient

    # - name: Deploy Borg clients
    #   ansible.builtin.import_role:
    #     name: borg_client
    #   when: "'borg_client' in group_names"
    #   tags: borg_client
    #   vars:
    #     borg_remote_server: "{{ hostvars[groups['backup_server'][0]][ansible_host] }}"
