---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Basic configuration
      ansible.builtin.import_role:
        name: essential
      tags: essential

    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      when: "'ingress' in group_names"
      tags: caddy
      vars:
        caddy_data_path: "/var/lib/caddy_c"
