---
- name: "Remote III: Borg setup"
  # notably these tasks have dependencies across hosts, so we can't use free execution as in Remote II
  hosts: all
  tasks:
    - name: Deploy Borg clients
      ansible.builtin.import_role:
        name: borg_client
      when: "'borg_client' in group_names"
      tags: borg_client
      vars:
        borg_remote_server: "{{ hostvars[groups['borg_server'][0]].ansible_host }}"

    - name: "Compile Borg client list"
      ansible.builtin.set_fact:
        borg_client_hosts: |
          {{
            borg_client_hosts | default([]) +
            groups['borg_client']
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: "Compile Borg pubkey list (servers)"
      ansible.builtin.set_fact:
        borg_ssh_pubkeys_servers: |
          {{
            dict(groups.borg_client | zip(groups.borg_client | map('extract', hostvars, 'borg_ssh_host_pubkey')))
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: "Compile Borg pubkey list (devices)"
      ansible.builtin.set_fact:
        borg_ssh_pubkeys: |
          {{
            borg_ssh_pubkeys | default({}) | combine(borg_ssh_pubkeys_servers)
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: Deploy Borg server
      ansible.builtin.import_role:
        name: borg_server
      when: "'borg_server' in group_names"
      tags: borg_server
      vars:
        # on the borg server, borg is the only service running
        borg_home_dir: "/vmdisk"
