---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Security tasks
      ansible.builtin.import_role:
        name: security
      tags: security
