---
- name: "Remote I: Pre-VM setup"
  hosts: hypervisors
  tasks:
    - name: Deploy keyfile
      ansible.builtin.copy:
        src: "lukskey.secret"
        dest: "/root/lukskey"
        mode: "u=rw,g=,o="
        owner: "root"
        group: "root"

    - name: Set up disks
      ansible.builtin.include_role:
        name: disks

    - name: Read controller SSH public key
      set_fact:
        controller_ssh_pubkey: "{{ lookup('file', controller_ssh_pubkey_path )}}"

    - name: Read controller VPN ONE public key
      set_fact:
        controller_vpn_pubkey: "{{ lookup('file', '/etc/systemd/network/network.wireguard.public.wg1')}}"

    - name: Generate WireGuard server keys (VPN ONE)
      ansible.builtin.include_role:
        name: wireguard-key
      vars:
        wireguard_interface: "wg1"

    - name: Retrieve WireGuard server pubkey (VPN ONE)
      ansible.builtin.set_fact:
        wg_server_pubkey: "{{ hostvars.localhost.wireguard_public_keys_wg1[groups.hypervisors[0]] }}"

    - name: Retrieve WireGuard server address (VPN ONE)
      ansible.builtin.set_fact:
        wg_server_addr: "{{ hostvars[groups.hypervisors[0]].ansible_host }}"

    - name: Generate WireGuard client configurations (VPN ONE)
      ansible.builtin.include_role:
        name: wireguard_quick_confs
      vars:
        wireguard_quick_server_pubkey: "{{ wg_server_pubkey }}"
        wireguard_quick_server_endpoint: "net.{{ domain_main }}"
        wireguard_quick_dns: "{{ hostvars[groups.ingress[0]].ansible_host }}"
        wireguard_quick_subnet: "{{ vpn1_subnet }}"

    - name: Save WireGuard server pubkey (VPN ONE)
      ansible.builtin.template:
        src: "raw.j2"
        dest: "~/wireguard-server-wg1.pub"
        mode: "u=rw,g=r,o=r"
      delegate_to: localhost
      become: false
      vars:
        content: "{{ wg_server_pubkey }}"

    - name: Save WireGuard server address (VPN ONE)
      ansible.builtin.template:
        src: "raw.j2"
        dest: "~/wireguard-server-addr"
        mode: "u=rw,g=r,o=r"
      delegate_to: localhost
      become: false
      vars:
        content: "{{ wg_server_addr }}"

    - name: Create virtual machines
      ansible.builtin.include_role:
        name: libvirt
      with_items: "{{ groups['domains'] }}"
      loop_control:
        loop_var: current_domain
      vars:
        libvirt_vm_name: "{{ current_domain }}"
        libvirt_mac_address: "{{ hostvars[current_domain].libvirt_mac_address }}"
        libvirt_vpn_addresses:
          - "{{ hostvars[current_domain].ansible_host }}/24" # note the /24 refers to the VPN subnet
        libvirt_vpn_interface: "wg1"
        libvirt_memory_mib: "{{ hostvars[current_domain].libvirt_memory_mib | default(false) }}"
        libvirt_cpu_count: "{{ hostvars[current_domain].libvirt_cpu_count | default(false) }}"
        libvirt_agent_user: "{{ admin_username }}"
        libvirt_agent_pubkey: "{{ controller_ssh_pubkey }}"
        libvirt_clean_image: "{{ hostvars[current_domain].libvirt_clean_image | default(libvirt_clean_image_default) }}"

    - name: "Compile peer list (VPN ONE): virtual machines"
      ansible.builtin.set_fact:
        wg_server_peers: |
          {{
            wg_server_peers | default([]) +
            [{
              'public_key': hostvars['localhost'].wireguard_public_keys_wg1[item],
              'allowed_ips': [hostvars[item].ansible_host + '/32'],
            }]
          }}
      with_items: "{{ groups['domains'] }}"

    - name: "Compile peer list (VPN ONE): Ansible controller host"
      ansible.builtin.set_fact:
        wg_server_peers: |
          {{
            wg_server_peers | default([]) +
            [{
              'public_key': controller_vpn_pubkey,
              'allowed_ips': [controller_vpn_ip + '/32'],
            }]
          }}

    - name: "Compile peer list (VPN ONE): User devices"
      ansible.builtin.set_fact:
        wg_server_peers: |
          {{
            wg_server_peers | default([]) +
            [{
              'public_key': item.public_key,
              'allowed_ips': [item.address + '/32'],
            }]
          }}
      with_items: "{{ wireguard_quick_clients }}"

    - name: WireGuard server setup (VPN ONE)
      ansible.builtin.include_role:
        name: wireguard
      vars:
        wireguard_interface: "wg1"
        wireguard_listen_port: 51820
        wireguard_description: "VPN ONE — WireGuard tunnel"
        wireguard_addresses:
          - "{{ bastion_vpn_ip }}/24"
        # note masquerade is not enabled because this is implemented by our nftables role
        wireguard_immediate: true
        wireguard_peers: "{{ wg_server_peers }}"

    - name: Configure sysctl
      ansible.builtin.import_role:
        name: sysctl
      vars:
        sysctl_ip_forwarding: true
      tags: sysctl-hypervisor
