---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Basic configuration
      ansible.builtin.import_role:
        name: essential
      tags: essential

    - name: Deploy test container
      ansible.builtin.import_role:
        name: test_http
      tags: test
      when: "inventory_hostname == 'harena03'"
