---
- name: "Remote II: post-VM setup"
  hosts: all
  tasks:
    - name: Setup firewall
      ansible.builtin.import_role:
        name: nftables
      tags: firewall

    - name: Basic configuration
      ansible.builtin.import_role:
        name: essential
      tags: essential

    - name: Setup disks (in VM)
      ansible.builtin.import_role:
        name: disks_vm
      when: "'domains' in group_names"
      tags: disks_vm

    - name: Deploy Caddy
      ansible.builtin.import_role:
        name: caddy
      when: "'ingress' in group_names"
      tags: caddy
      vars:
        caddy_data_path: "/var/lib/caddy_c"

    - name: Deploy DNS server
      ansible.builtin.import_role:
        name: dns
      when: "'ingress' in group_names"
      tags: dns
      vars:
        dns_listen_interfaces:
          - wg1
        dns_domains:
          - domain: "{{ dyndns_domain }}"
            ip_addr: "{{ bastion_vpn_ip }}"
          - domain: ".{{ domain_main }}"  # match all subdomains
            ip_addr: "{{ bastion_vpn_ip }}"

    - name: Configure resolv.conf
      ansible.builtin.import_role:
        name: resolv
      tags: resolv
      vars:
        resolv_fallback: "{{ dns_recurse_ips[0] }}"

    - name: Deploy HAProxy
      ansible.builtin.import_role:
        name: haproxy
      when: "'haproxy' in group_names"
      tags: haproxy

    - name: Deploy ddclient
      ansible.builtin.import_role:
        name: ddclient
      when: "'ingress' in group_names"
      tags: ddclient

    - name: Deploy Borg clients
      ansible.builtin.import_role:
        name: borg_client
      when: "'borg_client' in group_names"
      tags: borg_client
      vars:
        borg_remote_server: "{{ hostvars[groups['borg_server'][0]].ansible_host }}"

    - name: "Compile Borg client list"
      ansible.builtin.set_fact:
        borg_client_hosts: |
          {{
            borg_client_hosts | default([]) +
            groups['borg_client']
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: "Compile Borg pubkey list (servers)"
      ansible.builtin.set_fact:
        borg_ssh_pubkeys_servers: |
          {{
            dict(groups.borg_client | zip(groups.borg_client | map('extract', hostvars, 'borg_ssh_host_pubkey')))
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: "Compile Borg pubkey list (devices)"
      ansible.builtin.set_fact:
        borg_ssh_pubkeys: |
          {{
            borg_ssh_pubkeys | default({}) | combine(borg_ssh_pubkeys_servers)
          }}
      when: "'borg_server' in group_names"
      tags: borg_server

    - name: Deploy Borg server
      ansible.builtin.import_role:
        name: borg_server
      when: "'borg_server' in group_names"
      tags: borg_server
      vars:
        # on the borg server, borg is the only service running
        borg_home_dir: "/vmdisk"

    - name: Create Podman storage directory
      ansible.builtin.file:
        path: "/ext/podman"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
      when: "libvirt_enable_ext and 'domains' in group_names"
      tags: podman_dir

    - name: Deploy Radicale
      ansible.builtin.import_role:
        name: radicale
      when: "'radicale' in group_names"
      tags: radicale
      vars:
        radicale_data_path: "/vmdisk/radicale"
        radicale_config_path: "/vmdisk/radicale_conf"
        radicale_users: "{{ vault_radicale_users }}"
        podman_storage_path: "/ext/podman/radicale"

    - name: Deploy Navidrome
      ansible.builtin.import_role:
        name: navidrome
      when: "'navidrome' in group_names"
      tags: navidrome
      vars:
        navidrome_data_path: "/vmdisk/navidrome_data"
        navidrome_mus_path: "/vmdisk/navidrome_mus"
        podman_storage_path: "/ext/podman/navidrome"

    - name: Deploy Forgejo
      ansible.builtin.import_role:
        name: forgejo
      when: "'forgejo' in group_names"
      tags: forgejo
      vars:
        forgejo_data_path: "/vmdisk/forgejo"
        forgejo_domain: "git.{{ domain_main }}"
        podman_storage_path: "/ext/podman/forgejo"

    - name: Deploy Matrix
      ansible.builtin.import_role:
        name: matrix
      when: "'matrix' in group_names"
      tags: matrix
      vars:
        matrix_data_path: "/vmdisk/matrix"
        podman_storage_path: "/ext/podman/matrix"

    - name: Create Paperless directory
      ansible.builtin.file:
        path: "/vmdisk/paperless"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
      when: "'paperless' in group_names"

    - name: Deploy Paperless
      ansible.builtin.import_role:
        name: paperless
      when: "'paperless' in group_names"
      tags: paperless
      vars:
        paperless_data_path: "/vmdisk/paperless/data"
        paperless_cons_path: "/vmdisk/paperless/cons"
        paperless_media_path: "/vmdisk/paperless/media"
        paperless_export_path: "/vmdisk/paperless/export"
        podman_storage_path: "/ext/podman/paperless"
