---
argument_specs:
  main:
    short_description: "Setup a user to use Podman rootless containers."
    author: "dogeystamp <dogeystamp@disroot.org>"
    options:
      podman_user:
        description: "User to perform setup for."
        type: "str"
        required: true
