---
- name: Install Caddy
  ansible.builtin.package:
    name: caddy
    state: present

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "/etc/caddy/Caddyfile"
    owner: root
    group: caddy
    mode: "u=rw,g=r,o="
    validate: /usr/bin/caddy validate --adapter caddyfile --config %s
  register: caddy_conf

- name: Restart Caddy service
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
  when: caddy_conf.changed

- name: Enable Caddy
  ansible.builtin.systemd_service:
    name: caddy
    enabled: true
    state: started
