---
argument_specs:
  main:
    short_description: "Set up nftables rules directly."
    description: |
      This role sets up nftables without a frontend like firewalld.
      Configurations are hardcoded for my own use.
    author: "dogeystamp <dogeystamp@disroot.org>"
    options:
      nftables_preset:
        description: "Selects a configuration 'archetype'."
        type: "str"
        required: true
        choices:
          - "bastion"
          - "service"
          - "controller"

      nftables_internal_listens_tcp:
        description: "List of TCP ports / services to allow input for in the internal (VPN) network."
        type: "list"
        elements: "str"
        default: []

      nftables_internal_listens_udp:
        description: "List of UDP ports / services to allow input for in the internal (VPN) network."
        type: "list"
        elements: "str"
        default: []

      nftables_external_listens_tcp:
        description: "List of TCP ports / services to allow input for in the external network."
        type: "list"
        elements: "str"
        default: []

      nftables_external_listens_udp:
        description: "List of UDP ports / services to allow input for in the external network."
        type: "list"
        elements: "str"
        default: []
