---
# Default options for the entire playbook.

# Username for administrative users (used on all hosts)
admin_username: erus              # local admin
remote_admin_username: imperator  # remote management

controller_hostname: castellum


# Ansible Git repository options

# signature verification on repository
git_allowed_signers:
  - 'dogeystamp@disroot.org namespaces="git" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICsmYC1XDX747Bd9QVQRgQbp7HUcGhWIMBBVnlknPubV'
# repository itself (read only access)
git_repo: https://github.com/dogeystamp/ansible-homelab.git
git_branch: main


# Base image for VMs
libvirt_clean_image_default: "/disk/stat/vm/debian-13-nocloud-arm64.qcow2"
# VM data storage location
libvirt_vm_directory: "/disk/data/vm"

disk_dev: "/dev/sda1"


# Ansible connection parameters
ansible_user: "{{ admin_username }}"
ansible_connection: "ssh"


# Paths to a private and public SSH key; this is used to connect to the remote servers.
# The public key will also be deployed to VMs.
ansible_ssh_private_key_file: ~/.ssh/key
controller_ssh_pubkey_path: "{{ ansible_ssh_private_key_file }}.pub"

domain_main: dogeystamp.com
dns_localdomain: "n.{{ domain_main }}"
dns_recurse_ips:
  - 9.9.9.9
  - 1.1.1.1

# VPN ONE options
# Note that you can't just change this to change the subnet;
# change the IP addresses in the inventory too.
vpn1_subnet: "10.55.55.0/24"
vpn1_subnet_glob: "10.55.55.*"
controller_vpn_ip: "10.55.55.254"
bastion_vpn_ip: "10.55.55.1"

lan_subnet: "192.168.0.0/24"


# Vault options (see group_vars/vault-template.yml)
borg_passphrases: "{{ vault_borg_passphrases }}"
borg_client_hosts: "{{ vault_borg_client_hosts }}"
borg_ssh_pubkeys: "{{ vault_borg_ssh_pubkeys }}"

dyndns_domain: "{{ vault_dyndns_domain }}"
dyndns_password: "{{ vault_dyndns_password }}"

xandikos_pw_hash: "{{ vault_xandikos_pw_hash }}"

wireguard_quick_clients: "{{ vault_wireguard_quick_clients }}"

navidrome_tx_pubkeys: "{{ vault_navidrome_tx_pubkeys }}"
