---
- name: Install DNS packages
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Deploy dnsmasq configuration
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Disable systemd-resolved
  ansible.builtin.systemd_service:
    name: "systemd-resolved"
    state: stopped
    enabled: false
    masked: true

- name: Ensure dnsmasq is started
  ansible.builtin.systemd_service:
    name: "dnsmasq"
    state: started
    enabled: true
