---
- name: Install Borg packages
  ansible.builtin.package:
    name:
      - borgbackup
      - acl
    state: present

- name: Create Borg transfer user
  ansible.builtin.user:
    name: "borgtx"
    state: present
    create_home: true
    shell: "/bin/sh"
  register: borg_tx_user

- name: Setup authorized_keys for transfer user
  ansible.posix.authorized_key:
    user: "{{ borg_tx_user.name }}"
    state: present
    exclusive: true
    key: "{{ item }}"
    key_options: 'command="rrsync --ro {{ borg_home_dir }}",restrict'
  with_items: "{{ borg_tx_pubkeys }}"

- name: Create backup server users
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    create_home: true
    home: "{{ borg_home_dir }}/{{ item }}"
    shell: "/bin/sh"
  register: backup_users
  with_items: "{{ borg_client_hosts }}"

- name: Create backup server groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ borg_client_hosts }}"

- name: Add backup server users to their groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - "{{ item }}"
  with_items: "{{ borg_client_hosts }}"

- name: Add borg transfer user to backup groups
  ansible.builtin.user:
    name: "{{ borg_tx_user.name }}"
    groups:
      - "{{ item }}"
    append: true
  with_items: "{{ borg_client_hosts }}"

- name: Setup authorized_keys for backup users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: true
    key: "{{ borg_ssh_pubkeys[item.name] }}"
    # note the umask is set to allow the backup transfer user to read backups
    key_options: 'command="borg serve --umask 0027 --restrict-to-path {{ item.home }}/borg",restrict'
  with_items: "{{ backup_users.results }}"
