---
- name: Install Borg packages
  ansible.builtin.package:
    name: "borgbackup"
    state: present

- name: Create Borg transfer user
  ansible.builtin.user:
    name: "borgtx"
    state: present
    create_home: true
    shell: "/bin/sh"
  register: borg_tx_user

- name: Setup authorized_keys for transfer user
  ansible.posix.authorized_key:
    user: "{{ borg_tx_user.name }}"
    state: present
    exclusive: true
    key: "{{ item }}"
    key_options: 'command="rrsync --ro {{ borg_home_dir }}",restrict'
  with_items: "{{ borg_tx_pubkeys }}"

- name: Create backup server users
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    create_home: true
    home: "{{ borg_home_dir }}/{{ item }}"
    shell: "/bin/sh"
  register: backup_users
  with_items: "{{ borg_client_hosts }}"

- name: Set ACL on backup server user home directories
  ansible.posix.acl:
    path: "{{ item.home }}"
    default: true
    entity: "{{ borg_tx_user.name }}"
    etype: user
    permissions: "rX"
    # NOTE: i'm assuming here that borg repos don't have huge amounts of files;
    # in my experience ansible is super slow when recursing over more than like
    # a few thousand files
    recursive: true
    state: present
  with_items: "{{ backup_users.results }}"

- name: Setup authorized_keys for backup users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    exclusive: true
    key: "{{ borg_ssh_pubkeys[item.name] }}"
    key_options: 'command="borg serve --restrict-to-path {{ item.home }}/borg",restrict'
  with_items: "{{ backup_users.results }}"
