---
- name: Setup crypttab
  community.general.crypttab:
    backing_device: "{{ disk_dev }}"
    name: disk
    state: present
    password: /root/lukskey
  no_log: false  # this is just the password's path

- name: Decrypt disk
  luks_device:
    device: "{{ disk_dev }}"
    keyfile: /root/lukskey
    name: disk
    state: opened
  no_log: false  # this is just the password's path

- name: Setup fstab (main disk)
  mount:
    path: /disk
    src: /dev/mapper/disk
    state: mounted
    fstype: btrfs

- name: Setup fstab (VM disk)
  mount:
    path: /vmdata
    src: vmdata
    state: mounted
    fstype: virtiofs
  when: libvirt_enable_vmdisk
