---
# See meta/argument_specs.yml for information on how to use this role.

- name: Configure systemd netdev
  ansible.builtin.template:
    dest: "{{ wireguard_path }}/{{ wireguard_interface }}.netdev"
    src: wgx.netdev.j2
    owner: "{{ wireguard_file_owner }}"
    group: "{{ wireguard_file_group }}"
    mode: u=rw,g=r,o=
  notify: Reload systemd-networkd

- name: Configure systemd network
  ansible.builtin.template:
    dest: "{{ wireguard_path }}/{{ wireguard_interface }}.network"
    src: wgx.network.j2
    owner: "{{ wireguard_file_owner }}"
    group: "{{ wireguard_file_group }}"
    mode: u=rw,g=r,o=
  notify: Reload systemd-networkd

- name: Apply changes
  ansible.builtin.meta: flush_handlers
